### ISSUE TITLE
Truck

### ISSUE THREAD

**Issue by beardofedu** [beardofedu/truck-yea#1]
![20180508_010828](https://user-images.githubusercontent.com/18329853/39771449-3ea80b66-52c0-11e8-8401-a772248fb3c3.jpg)

**Comment by beardofedu** [comment]
![20180508_010910](https://user-images.githubusercontent.com/18329853/39771456-42fe684a-52c0-11e8-96ff-798b13448418.jpg)

**Comment by brianamarie** [comment]
@hectorsector @a-a-ron @hollenberry @jasonetco plz post help tho

**Comment by hectorsector** [comment]
Check #8 @brianamarie

**Comment by a-a-ron** [comment]
![img_0829](https://user-images.githubusercontent.com/6351798/39871485-10f9fea8-5433-11e8-9695-783a09aced40.JPG)
![img_0165](https://user-images.githubusercontent.com/6351798/39871495-124ff528-5433-11e8-8818-47f361130737.JPG)
![img_7925](https://user-images.githubusercontent.com/6351798/39871498-13c39e82-5433-11e8-9f34-5db779882f58.JPG)
![img_1741](https://user-images.githubusercontent.com/6351798/39871501-159cd0e8-5433-11e8-946b-e2c3f2d78f39.JPG)

**Comment by hectorsector** [comment]
Moved to #6
