### ISSUE TITLE
Trailer

### ISSUE THREAD

**Issue by beardofedu** [beardofedu/truck-yea#2]
![20180508_002530](https://user-images.githubusercontent.com/18329853/39771400-0b2fe452-52c0-11e8-9164-22f22ac2fea5.jpg)

MMMM 🍗

**Comment by beardofedu** [comment]
![20180508_002554](https://user-images.githubusercontent.com/18329853/39771534-8be409d4-52c0-11e8-8a52-a2f63ad88895.jpg)

**Comment by a-a-ron** [comment]
![img_9743](https://user-images.githubusercontent.com/6351798/39871307-5fc3a9a4-5432-11e8-8f8f-2bc86834fa4d.JPG)
![img_7778](https://user-images.githubusercontent.com/6351798/39871313-63c45698-5432-11e8-9d78-4479e4caac34.JPG)

**Comment by brianamarie** [comment]
![img_0163](https://user-images.githubusercontent.com/9906718/39871204-1a0ca3a2-5432-11e8-9dd9-c9e1f7623763.JPG)
![img_0164](https://user-images.githubusercontent.com/9906718/39871205-1a6dd24e-5432-11e8-9cdc-dbd7e33eb0ef.JPG)

**Comment by hectorsector** [comment]
Moved to #6
