### ISSUE TITLE
Helicopter steps 6-12

### ISSUE THREAD

**Issue by hectorsector** [beardofedu/truck-yea#7]
![img_1328](https://user-images.githubusercontent.com/16547949/39871243-34e173ec-5432-11e8-8390-c74806757705.JPG)
![img_0089](https://user-images.githubusercontent.com/16547949/39871366-8be63f2e-5432-11e8-9437-88f347d8687e.JPG)
![img_2327](https://user-images.githubusercontent.com/16547949/39871367-8e0437fc-5432-11e8-8202-c07874eab7eb.JPG)

**Comment by brianamarie** [comment]
![img_0166](https://user-images.githubusercontent.com/9906718/39871718-bb2068f4-5433-11e8-8e02-1a5823114e0b.JPG)
![Uploading IMG_0161.JPG…]()
![img_0165](https://user-images.githubusercontent.com/9906718/39871720-bbbcd9be-5433-11e8-8b17-867ce93bc0a3.JPG)
![img_0162](https://user-images.githubusercontent.com/9906718/39871723-bc1919d6-5433-11e8-9f96-4d4cfda3c92b.JPG)

**Comment by hectorsector** [comment]
@brianamarie this didn't upload:

> Uploading IMG_0161.JPG…

**Comment by hollenberry** [comment]
@brianamarie Are we missing any extra instructions for the helicopter? Looks like a few might be for the trailer.

**Comment by hectorsector** [comment]
All instructions have been moved to #6
