### ISSUE TITLE
Truck steps 20-26

### ISSUE THREAD

**Issue by hectorsector** [beardofedu/truck-yea#8]
![img_6133](https://user-images.githubusercontent.com/16547949/39871567-4bf73d2c-5433-11e8-817f-13a884c407df.JPG)
![img_3724](https://user-images.githubusercontent.com/16547949/39871578-52093512-5433-11e8-84cb-396358e0af4d.JPG)
![img_3215](https://user-images.githubusercontent.com/16547949/39871585-574a739c-5433-11e8-83eb-6e47eaac3add.JPG)
![img_4585](https://user-images.githubusercontent.com/16547949/39871586-5869728c-5433-11e8-9e6d-1d125011d986.JPG)

**Comment by beardofedu** [comment]
[30](https://github.com/githubschool/dow-dmc/blob/beep-beep/missing-pages/20180320_220415.jpg)

[32](https://github.com/githubschool/dow-dmc/blob/beep-beep/missing-pages/20180320_220429.jpg)

**Comment by hectorsector** [comment]
All these steps moved to #6
